### ISSUE TITLE
Reported coordinates seem shifted

### ISSUE THREAD

**Issue by Phlya** [koszullab/chromosight#24]
Hello, thank you for this tool - I just tried to use it to call loops with default settings and the results look very good! The only issue is that I have a feeling that the reported coordinates are shifted by ~1-2 pixels relative to the actual highest point in the peak. Here is an example three calls, all just off the pixel with the highest value. Is it possible chromosight selects a wrong pixel from the neighborhood?
![Screenshot from 2020-04-15 12-34-41](https://user-images.githubusercontent.com/2895034/79332898-8758b580-7f15-11ea-9e7f-3fc1838133bc.png)

Do you observe anything like this?

I just used the file from here and called at 5 kb resolution, if you want to reproduce this, and looked in higlass. https://data.4dnucleome.org/files-processed/4DNFIFLDVASC/ I installed chromosight using conda.

Thanks again for developing and sharing this tool!

**Comment by cmdoret** [comment]
Hi !
Glad to know it's useful :)

Yes sometimes the pixel with the highest correlation with the kernel is next to the pixel with the pixel with the highest contacts. Reducing the kernel size using a smaller `--win-size` value can help (correlations are computed using a smaller neighbourhood, so distant pixels are less likely to interfere). This might also have the side effect of increasing the number of false positives.

Coordinates very close to the diagonal can also be shifted. This happens when the kernel overlaps the lower triangle. This is fixed using the `--full` option, which applies a "missing mask" taken into account when computing correlations. Pixels below the diagonal, or in missing bins are excluded from the calculations. This option slightly increases run time and memory usage, but it seems to yield more accurate results, so it might become the default in version 1.0.0.

Thanks for the feedback !

**Comment by Phlya** [comment]
Thanks, I'll explore these options!
