### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by sarah872** [koszullab/chromosight#34]
Hi,
thanks for the handy tool!
I wanted to ask if you could provide some code on how to label the loops, e.g. based on the order from the output file. This would make it easer to extract the coordinates from the file of a single loop I am interested in.
Also, how do I plot the chromosome coordinates on the axes instead of the bin number?
Thank you in advance!

**Comment by cmdoret** [comment]
Hello @sarah872,

To plot coordinates on the axis, if you are using matplotlib to display the matrix, you need to use custom axis ticks.
Here is a tutorial on how to do this: https://www.tutorialspoint.com/matplotlib/matplotlib_setting_ticks_and_tick_labels.htm

The two lines of interest are:
```python
ax.set_xticks([0,2,4,6])
ax.set_xticklabels(['zero','two','four','six'])
```
Where, in your case you would need to figure out the mapping between row number and coordinates to write instead.

As for "labelling the loops", I'm not sure what you mean. there are two output files, the text (tsv) file with loop coordinates, and the json or npy file containing the loop images. If you know the coordinates of a particular loop (from the tsv file) and want to get its image, it's easy because loops are saved in the same order in both files.

So for example, if your loop is the 4th in the tsv file, it will also be the 4th in the other file.
> Note: Since we're using python, numbering starts from 0 and the 4th means index 3

If the file is in json format, you could do:

```python
import matplotlib.pyplot as plt
import json
loop_imgs = json.load(open('output.json'))
plt.imshow(loop_imgs["3"])
plt.show()
```

I hope that helps

**Comment by sarah872** [comment]
Thank you!
So I think adding something like this works to make show chromosome locations:
```
def maketicks(maximum=mat.shape[1],step=100):
    x = []
    for n in range(0,maximum,step):
        x.append(n)
    x.append(mat.shape[1])
    return x
ax.set_xticks(maketicks())
ax.set_xticklabels([str(i*5) for i in maketicks()])
```

As for the second questions, I just wanted to have a little number next to each circle in the main heatmap.
I just found out that the matrix is plotted based on bins, and not on any other coordinates -.-

```
for i in range(loops.shape[0]):
    plt.annotate(str(i+1), (loops.bin1[i], loops.bin2[i]), (loops.bin2[i]+5 , loops.bin1[i]+5))
```

Thanks for pointing me in the right direction!
