### ISSUE TITLE
Empty score fields in quantify results

### ISSUE THREAD

**Issue by PerrineLacour** [koszullab/chromosight#35]
Hello!

I used chromosight quantify to compare two conditions (as describe in the documentation) and it worked overall, but I saw that some rows had empty score, pvalue and qvalue fields. Do you know why this happens for some rows? Does this correspond to masked bins in the HiC matrix?
Should I remove these rows for the rest of the analysis?

Best,

Perrine

**Comment by cmdoret** [comment]
Hi @PerrineLacour,

Indeed the entries with missing values were skipped by Chromosight because they do not pass the default thresholds.
There are 2 such filters:
* `--perc-zero`: the percentage of pixels with 0 contacts in the window
* `--perc-undetected`: the percentage of missing pixels in the window

Missing means the entire row / column was discarded due to low coverage (repeated regions).
Chromosight discards these entries to prevent unstable / inaccurate scores.

This is because the scores would be computed on fewer valid pixels, but if you really want to keep them, you can set the two options above to 100, effectively computng scores for all windows even if there is only a single nonzero pixel.

I hope that helps,
Cyril

**Comment by PerrineLacour** [comment]
Hi @cmdoret ,

Thank you for your answer! 
I was wondering, since the regions were detected in the control and used for `quantify` on the other condition, they should not be repeated regions. If they have low coverage in the mutant, could it mean that the feature is lost in the mutant and that I should then consider them rather than discard them?

Best, 

Perrine

**Comment by cmdoret** [comment]
You're right, if you detected the patterns in the control, it's unlikely to be due to repeated regions.

It is possible that the feature was lost, indeed. Just make sure you subsample both the control and mutant to the same number of contacts (`--subsample` option).

One last thing: due to technical variations the features can differ slightly between replicates (e.g. Shifted by 1 pixel). This means that the sample used for detection will likely have slightly better scores than the others overall.

There are a few workarounds:
* Use a different control replicate for quantification and detection.
* Do the detection on the merged matrix of subsampled control and mutant, then quantification separately on each condition.
* Verify if results are the same when doing detection on mutant and quantification on control.

**Comment by cmdoret** [comment]
I'm closing this issue, but if you have other questions, don't hesitate to reopen !
