### ISSUE TITLE
Use chromosight to quantify chromatin interactions on domain (TAD or local domains) 

### ISSUE THREAD

**Issue by Linhua-Sun** [koszullab/chromosight#43]
Hi: 
    Thank you very much for developing such an excellent software. It's gonna be so awesome. I am testing chromosight in Hi-C datasets from plants. **I am interested in whether chromosight can be applied to quantify the chromatin interactions (strength) on domains (or say TAD, TAD-like domains, those local triangle-shaped domains).** Like, we can score the chromatin strength of targeted regions in sample A and sample B. Thus, we can integrated the Hi-C datasets with RNA-Seq etc.
Thanks.
Linhua

**Comment by cmdoret** [comment]
Hello @Linhua-Sun,

Thanks for the kind words !

So it depends what you mean by interaction strength on TADs. Chromosight can measure the intensity of patterns (contrasts).
In your case you could use chromosight for border detection / quantification with the option `--pattern borders` to measure the insulation strength of domains on the diagonal.

* If you don't have TADs borders coordinates, you could use `chromosight detect` to find them and quantify their intensities at the same time.
* If you already have TAD coordinates, you could feed those coordinates to chromosight quantify so that it computes their intensities in the two samples separately.

Here's the tutorial for loops, but it should be fairly similar for TADs: https://chromosight.readthedocs.io/en/latest/notebooks/g1_metaphase_yeast_example.html

An more complicated alternative we have not explored much would be to compute the contrast at the top corner of the domain (not on the diagonal). For this you would need to create a custom kernel that looks like this:
![image](https://user-images.githubusercontent.com/22558602/109309419-2be89b00-783b-11eb-89a4-7f6b226c2823.png)

For this, first you need to generate a template kernel config json file (e.g. "corners"):

`chromosight generate-config corners`

And an associated kernel matrix. This can be done quite easily in python:
```python
import numpy as np
import json

# Generate a corner kernel
corner_kernel = np.zeros((17, 17))
hw = corner_kernel.shape[0] // 2
corner_kernel[hw:, :hw] = 1

# Load config into a dict and edit it (could be done in a text editor instead)
cfg = json.load(open('corners.json'))
cfg['name'] = 'corners'
cfg['max_dist'] = 200000 # Maximum expected TAD size

# Save modified config file
with open('corners.json', 'w') as cfg_handle:
    json.dump(cfg, cfg_handle, indent=4)

# Save kernel
np.savetxt(cfg['kernels'][0], corner_kernel)
```

Then you could just use that kernel by running:
`chromosight detect --kernel-config corners.json sample.cool outdir`

**Comment by cmdoret** [comment]
Since it's been a while, I'll close the issue. But if you still have questions / problems don't hesitate to reopen.

**Comment by Linhua-Sun** [comment]
Thank you very much for your timely reply. I didn't note to this notice from  @github. I'm sorry for the late reply. Your reply is very helpful to us. We are testing the code on Arabidopsis thaliana and other plants.

**Comment by cmdoret** [comment]
Hi @Linhua-Sun , I just wanted to notify you that there was a bug in #46 causing `quantify` to return lower scores than `detect` when using the borders pattern. I fixed the issue, so you may want to update to v1.5.0.

**Comment by Linhua-Sun** [comment]
Thank you very much for your reminding！This software is so cool!
