### ISSUE TITLE
Detection doesn't report loops that should pass the Pearson threshold

### ISSUE THREAD

**Issue by PerrineLacour** [koszullab/chromosight#45]
Hello,

I was wondering how the detection step was deciding which coordinates to report. We have a gold standard set of loops that were manually annotated and I am trying to find the best overlap with those. Some loops were not found by ```detect``` even if when using ```quantify``` on with these sets of coordinates, they had a score that should have passed the Pearson threshold. They are not close to other loops that could have interfered.

I also saw that when just changing the Pearson parameter while running ```detect```, I get some unexpected behaviour: when I lower the threshold, I get more loops called, but I also lose some of them.

Do you know why this is happening?

Best,

**Comment by cmdoret** [comment]
Hi @PerrineLacour,

Yes this is a common issue when lowering the pearson threshold too much.

The convolution of the Hi-C map with the kernel yields a matrix of Pearson coefficients.

We then apply thresholding to binarize that map and use connected component labelling to separate patches of nonzero values.

Finally we use the coordinate of the best coefficient in each patch to detect the pattern.

When lowering the pearson threshold, new patches will appear (additional detections), but existing patches will also become larger and merge intto a single patch.

When that happens, we will get only 1 single detection instead of 2.

Does that make sense ?

**Comment by PerrineLacour** [comment]
Thank you for your answer, yes that makes perfect sense!

So then the parameter ```min-separation``` is used after this step and discards the lowest of two close but separate patches, is that right?

**Comment by cmdoret** [comment]
Exactly ! So if the patches got merged in the previous steps, reducing min-separation will not help.

**Comment by PerrineLacour** [comment]
Ok thank you a lot, I will stop using a low Pearson threshold then!
